version: '3.8'

services:
  products:
    build: ./products
    ports:
      - "3001:3001"
    networks:
      - ecommerce-network

  orders:
    build: ./order
    ports:
      - "3002:3002"
    depends_on:
      - products
      - redis
      - db
    networks:
      - ecommerce-network

  payments:
    build: ./payments
    ports:
      - "3003:3003"
    depends_on:
      - orders
    networks:
      - ecommerce-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ecommerce-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

volumes:
  db_data:

networks:
  ecommerce-network:
    driver: bridge
